(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["components/wui-sticky/wui-sticky"],{2206:function(t,e,n){},"6d99":function(t,e,n){"use strict";(function(t){Object.defineProperty(e,"__esModule",{value:!0}),e.default=void 0;var n={name:"wui-sticky",props:{offsetTop:{type:[Number,String],default:0},index:{type:[Number,String],default:""},enable:{type:Boolean,default:!0},h5NavHeight:{type:[Number,String],default:0},bgColor:{type:String,default:"#ffffff"},zIndex:{type:[Number,String],default:""}},data:function(){return{fixed:!1,height:"auto",stickyTop:0,elClass:this.$util.guid(),left:0,width:"auto"}},watch:{offsetTop:function(t){this.initObserver()},enable:function(t){0==t?(this.fixed=!1,this.disconnectObserver("contentObserver")):this.initObserver()}},computed:{uZIndex:function(){return this.zIndex?this.zIndex:970}},mounted:function(){this.initObserver()},methods:{getRect:function(e){var n=this;return new Promise((function(i){t.createSelectorQuery().in(n)["select"](e).boundingClientRect((function(t){i(t)})).exec()}))},initObserver:function(){var e=this;this.enable&&(this.stickyTop=0!=this.offsetTop?t.upx2px(this.offsetTop):0,this.disconnectObserver("contentObserver"),this.getRect("."+this.elClass).then((function(t){e.height=t.height,e.left=t.left,e.width=t.width,e.$nextTick((function(){e.observeContent()}))})))},observeContent:function(){var t=this;this.disconnectObserver("contentObserver");var e=this.createIntersectionObserver({thresholds:[.95,.98,1]});e.relativeToViewport({top:-this.stickyTop}),e.observe("."+this.elClass,(function(e){t.enable&&t.setFixed(e.boundingClientRect.top)})),this.contentObserver=e},setFixed:function(t){var e=t<this.stickyTop;e?this.$emit("fixed",this.index):this.fixed&&this.$emit("unfixed",this.index),this.fixed=e},disconnectObserver:function(t){var e=this[t];e&&e.disconnect()}},beforeDestroy:function(){this.disconnectObserver("contentObserver")}};e.default=n}).call(this,n("543d")["default"])},"6e40":function(t,e,n){"use strict";n.r(e);var i=n("6d99"),s=n.n(i);for(var r in i)"default"!==r&&function(t){n.d(e,t,(function(){return i[t]}))}(r);e["default"]=s.a},"6fdc":function(t,e,n){"use strict";n.r(e);var i=n("9dfd"),s=n("6e40");for(var r in s)"default"!==r&&function(t){n.d(e,t,(function(){return s[t]}))}(r);n("95c3");var o,c=n("f0c5"),u=Object(c["a"])(s["default"],i["b"],i["c"],!1,null,"ffbdacba",null,!1,i["a"],o);e["default"]=u.exports},"95c3":function(t,e,n){"use strict";var i=n("2206"),s=n.n(i);s.a},"9dfd":function(t,e,n){"use strict";var i;n.d(e,"b",(function(){return s})),n.d(e,"c",(function(){return r})),n.d(e,"a",(function(){return i}));var s=function(){var t=this,e=t.$createElement;t._self._c},r=[]}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'components/wui-sticky/wui-sticky-create-component',
    {
        'components/wui-sticky/wui-sticky-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('543d')['createComponent'](__webpack_require__("6fdc"))
        })
    },
    [['components/wui-sticky/wui-sticky-create-component']]
]);
