(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["pages/goods/category/components/LevelOne"],{"1bad":function(t,e,n){"use strict";n.r(e);var i=n("be08"),o=n.n(i);for(var a in i)"default"!==a&&function(t){n.d(e,t,(function(){return i[t]}))}(a);e["default"]=o.a},7860:function(t,e,n){"use strict";n.d(e,"b",(function(){return o})),n.d(e,"c",(function(){return a})),n.d(e,"a",(function(){return i}));var i={wuiGoodsCard:function(){return n.e("components/wui-goods-card/wui-goods-card").then(n.bind(null,"215a"))},wuiEmpty:function(){return Promise.all([n.e("common/vendor"),n.e("components/wui-empty/wui-empty")]).then(n.bind(null,"d0ab"))},wuiLoadingMore:function(){return n.e("components/wui-loading-more/wui-loading-more").then(n.bind(null,"90ab"))}},o=function(){var t=this,e=t.$createElement;t._self._c},a=[]},8212:function(t,e,n){"use strict";var i=n("d729"),o=n.n(i);o.a},be08:function(t,e,n){"use strict";Object.defineProperty(e,"__esModule",{value:!0}),e.default=void 0;var i={name:"GoodsCategoryLevelOne",props:{top:{type:Number,default:0},height:{type:Number,default:0},type:{type:[Number,String],default:1},parent:{type:[Number,String],default:0},data:{type:Array,default:function(){return[]}}},data:function(){return{list:null,loadMore:!1,lastPage:1,query:{page:1,id:0}}},watch:{parent:{handler:function(t){2==this.type&&(this.loading=!0,this.list=null,this.query.page=1,this.query.id=t,this.getList())},immediate:!0}},methods:{reachBottom:function(){!this.loadMore&&this.lastPage>this.query.page&&(this.loadMore=!0,this.query.page+=1,this.getList())},getList:function(){var t=this;this.loadMore=!0,this.$get("/goods/category/item",this.query).then((function(e){var n=e.data;t.lastPage=n.last_page,t.list||(t.list=[]),t.list=t.list.concat(n.data)})).finally((function(){t.loadMore=!1}))},sku:function(t){this.$emit("sku",t)},redirectGoods:function(t){this.$util.redirect("/pages/goods/detail/index?id=".concat(t))},redirect:function(t,e){this.$emit("redirect",t,e)}}};e.default=i},d729:function(t,e,n){},f56c:function(t,e,n){"use strict";n.r(e);var i=n("7860"),o=n("1bad");for(var a in o)"default"!==a&&function(t){n.d(e,t,(function(){return o[t]}))}(a);n("8212");var r,u=n("f0c5"),s=Object(u["a"])(o["default"],i["b"],i["c"],!1,null,"4f9a9be4",null,!1,i["a"],r);e["default"]=s.exports}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'pages/goods/category/components/LevelOne-create-component',
    {
        'pages/goods/category/components/LevelOne-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('543d')['createComponent'](__webpack_require__("f56c"))
        })
    },
    [['pages/goods/category/components/LevelOne-create-component']]
]);
