(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["pages/goods/category/components/LevelTwo"],{"1ae7":function(t,e,n){"use strict";n.r(e);var i=n("d09d"),a=n.n(i);for(var o in i)"default"!==o&&function(t){n.d(e,t,(function(){return i[t]}))}(o);e["default"]=a.a},"23c5":function(t,e,n){"use strict";n.d(e,"b",(function(){return a})),n.d(e,"c",(function(){return o})),n.d(e,"a",(function(){return i}));var i={wuiTag:function(){return n.e("components/wui-tag/wui-tag").then(n.bind(null,"2dd1"))},wuiGoodsCard:function(){return n.e("components/wui-goods-card/wui-goods-card").then(n.bind(null,"215a"))},wuiEmpty:function(){return Promise.all([n.e("common/vendor"),n.e("components/wui-empty/wui-empty")]).then(n.bind(null,"d0ab"))},wuiLoadingMore:function(){return n.e("components/wui-loading-more/wui-loading-more").then(n.bind(null,"90ab"))}},a=function(){var t=this,e=t.$createElement;t._self._c},o=[]},"69ac":function(t,e,n){"use strict";var i=n("9dd1"),a=n.n(i);a.a},"9dd1":function(t,e,n){},d09d:function(t,e,n){"use strict";Object.defineProperty(e,"__esModule",{value:!0}),e.default=void 0;var i={name:"GoodsCategoryLevelTwo",props:{top:{type:Number,default:0},height:{type:Number,default:0},type:{type:[Number,String],default:1},parent:{type:[Number,String],default:0},data:{type:Array,default:function(){return[]}}},data:function(){return{loading:!0,active:0,category:[],list:null,loadMore:!1,lastPage:0,scrollIndex:"id_0",query:{page:1,id:0}}},computed:{current:function(){var t=this,e=0;return this.category.forEach((function(n,i){i==t.active&&(e=n.id)})),e}},watch:{parent:{handler:function(t){var e=this;this.active=0,this.category=[],this.data.forEach((function(n){n.id==t&&n.children&&(e.category=n.children)}))},immediate:!0},current:{handler:function(t){2==this.type&&(this.loading=!0,this.list=null,this.query.page=1,this.query.id=t,this.getList())},immediate:!0}},methods:{reachBottom:function(){!this.loadMore&&this.lastPage>this.query.page&&(this.loadMore=!0,this.query.page+=1,this.getList())},getList:function(){var t=this;this.loadMore=!0,this.$get("/goods/category/item",this.query).then((function(e){var n=e.data;t.lastPage=n.last_page,t.list||(t.list=[]),t.list=t.list.concat(n.data)})).finally((function(){t.loadMore=!1}))},changeActive:function(t){this.active=t.currentTarget.dataset.index,this.checkScroll()},checkScroll:function(){this.scrollIndex=this.active>1?"id_".concat(this.active-1):"id_0"},sku:function(t){this.$emit("sku",t)},redirectGoods:function(t){this.$util.redirect("/pages/goods/detail/index?id=".concat(t))},redirect:function(t,e){this.$emit("redirect",t,e)}}};e.default=i},eaf6:function(t,e,n){"use strict";n.r(e);var i=n("23c5"),a=n("1ae7");for(var o in a)"default"!==o&&function(t){n.d(e,t,(function(){return a[t]}))}(o);n("69ac");var r,u=n("f0c5"),c=Object(u["a"])(a["default"],i["b"],i["c"],!1,null,"567b17de",null,!1,i["a"],r);e["default"]=c.exports}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'pages/goods/category/components/LevelTwo-create-component',
    {
        'pages/goods/category/components/LevelTwo-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('543d')['createComponent'](__webpack_require__("eaf6"))
        })
    },
    [['pages/goods/category/components/LevelTwo-create-component']]
]);
