(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["components/wui-share/wui-share"],{"010b":function(t,n,e){},"22cd":function(t,n,e){"use strict";var o=e("010b"),i=e.n(o);i.a},2890:function(t,n,e){"use strict";Object.defineProperty(n,"__esModule",{value:!0}),n.default=void 0;var o=i(e("3ee1"));function i(t){return t&&t.__esModule?t:{default:t}}var u={name:"wui-share",props:{show:{type:Boolean,default:!1},goodsId:{type:Number,default:0}},data:function(){return{shareShow:!1,windowShow:!1,shareWechatShow:!1,friendImage:o.default.root+"/assets/uniapp/share/friend.png",posterImage:o.default.root+"/assets/uniapp/share/poster.png",linkImage:o.default.root+"/assets/uniapp/share/link.png",id:0,type:0,image:""}},computed:{showFriendImage:function(){return!0}},watch:{show:{handler:function(t){this.shareShow=t},immediate:!0},goodsId:{handler:function(t){this.id=t},immediate:!0}},created:function(){this.type=1},methods:{poster:function(){var t=this;this.$util.showLoading(),this.$get("/goods/poster",{id:this.id,type:this.type}).then((function(n){t.image=n.data,t.windowShow=!0,t.close()})).catch((function(t){})).finally((function(){t.$util.hideLoading()}))},friend:function(){this.$util.isWechat()&&(this.close(),this.shareWechatShow=!0)},copy:function(){this.$util.copy(window.location.href)},close:function(){this.$emit("update:show",!1)}}};n.default=u},"68ba":function(t,n,e){"use strict";e.d(n,"b",(function(){return i})),e.d(n,"c",(function(){return u})),e.d(n,"a",(function(){return o}));var o={wuiPopup:function(){return e.e("components/wui-popup/wui-popup").then(e.bind(null,"418e"))},wuiBottomAction:function(){return e.e("components/wui-bottom-action/wui-bottom-action").then(e.bind(null,"4892"))},wuiBottomActionButton:function(){return e.e("components/wui-bottom-action-button/wui-bottom-action-button").then(e.bind(null,"456c"))},wuiWindow:function(){return e.e("components/wui-window/wui-window").then(e.bind(null,"5e66"))},wuiShareWechat:function(){return e.e("components/wui-share-wechat/wui-share-wechat").then(e.bind(null,"7f68"))}},i=function(){var t=this,n=t.$createElement;t._self._c},u=[]},"8d82":function(t,n,e){"use strict";e.r(n);var o=e("2890"),i=e.n(o);for(var u in o)"default"!==u&&function(t){e.d(n,t,(function(){return o[t]}))}(u);n["default"]=i.a},d63c:function(t,n,e){"use strict";e.r(n);var o=e("68ba"),i=e("8d82");for(var u in i)"default"!==u&&function(t){e.d(n,t,(function(){return i[t]}))}(u);e("22cd");var a,c=e("f0c5"),r=Object(c["a"])(i["default"],o["b"],o["c"],!1,null,"9c5d438e",null,!1,o["a"],a);n["default"]=r.exports}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'components/wui-share/wui-share-create-component',
    {
        'components/wui-share/wui-share-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('543d')['createComponent'](__webpack_require__("d63c"))
        })
    },
    [['components/wui-share/wui-share-create-component']]
]);
